#ifndef BT_TRANSACTIONTYPE_HPP
#define BT_TRANSACTIONTYPE_HPP

// from our POV
typedef enum {
    TRANS_SOCKET_ERROR = -128,
    TRANS_CLOSE_SOCKET = 0,
    TRANS_RECV_MATCH = 1,
    TRANS_RECV_TABLET_INFO = 2,
    TRANS_SEND_LOCAL_DB_HASH = 3,
    TRANS_SEND_LOCAL_DB = 4
} TRANSACTIONTYPE;

#endif